### ISSUE TITLE
AN/ASN-41 navigation panel keybinds do not function

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#231] opened 2020-06-21 12:37 UTC
**Describe the bug**
The keybinds for CW/CCW input of Destination and Present Position coordinates do not work when in the aircraft.

**To Reproduce**
1. Assign keybinds, like this: https://i.imgur.com/vrDaJfh.jpg
2. Try to use them on the Sim, they have no effect, like this: https://i.imgur.com/MUrtPxl.jpg

**Expected behavior**
Each press of these keys, should increase or decrease the counter values by 1. Holding the key down should autorepeat.

**Screenshots**
![Image 1](https://i.imgur.com/vrDaJfh.jpg)

![Image 2](https://i.imgur.com/MUrtPxl.jpg)

**Software Information (please complete the following information):**
 - DCS Version: DCS/2.5.6.50979
 - A-4E Version [e.g. v1.4]

**Additional context**
These keybinds would be really useful, as adjusting coordinates using the mouse is too cumbersome as it doesn't support dragging up-down like on other DCS aircrafts.

**Comment by rudel-chw** [comment] 2020-09-29 20:06
Hi, just wanted to report that this Bug is still present on v1.4.1 of the A-4E.

**Comment by heclak** [comment] 2020-09-30 00:31
Hi. Turns out that the keybinds were created but the functionality was never coded. I've been working on them but it will take a bit of time to finish and test them.

**Comment by Sparkowl** [comment] 2020-10-17 22:57
I had an encoder assigned to that function and it worked until I changed to v1.4.2 and deleted all my keybindings. 
The only issue I had before was that I had to press the button for the coordinates of D2.
Now I can't even find a keybinding for the knob pressing.

**Comment by callmepartario** [comment] 2021-04-23 18:24
heclak has begun work on the electric slew knobs. once i get the go-head, i will add some friendly keybinds for these unfinished functions.

**Comment by callmepartario** [comment] 2021-05-08 15:31
these are now working as intended; thanks, hecklak

**Closed by callmepartario** 2021-05-08 15:31 UTC
Labels: Bug, Code/LUA, TEST/resolve
