### ISSUE TITLE
engine cuts off if auto pause left on for too long

### ISSUE THREAD

**Issue by VRFlightGuyinPJPants** [heclak/community-a4e-c#339] opened 2021-04-24 10:08 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta]
 - A-4E Version [e.g. v1.3]

**Additional context**

**Comment by VRFlightGuyinPJPants** [comment] 2021-04-24 10:10
When Auto Pause is on during the start of a mission, after a short while, the “Fuel Pump” warning light turns on and after another short while, the engine shuts down by itself.

DCS Versions: both V2.5 and V2.7 OB
A-4E Version: 2.0 Beta-3

**Comment by callmepartario** [comment] 2021-04-29 13:51
confirmed -- i believe this is possibly fuel flow system related

**Comment by callmepartario** [comment] 2021-06-26 23:51
closing this due to lack of reproducibility.

**Closed by callmepartario** 2021-06-26 23:51 UTC
Labels: TEST/reproduce
