### ISSUE TITLE
Clickable cockpit feature loss

### ISSUE THREAD

**Issue by vfaco** [heclak/community-a4e-c#403] opened 2021-06-14 18:03 UTC
Periodically the cockpit mouse click feature completely fails and the icon becomes a yellow cross. The aircraft continues to fly normally and features are available via keyboard and hotas. Then suddenly it starts working for no apparent reason.   A-4E-C_v2.0.0-beta-5.1. Not using VR.

https://user-images.githubusercontent.com/85186251/121937397-a7058c80-cd18-11eb-93d0-ecb742953b0f.mp4

A track file of the clickable failure is here. However, the problem does not show in the track playback. In the sim the icon is stays a yellow cross; in the playback it appears normal. I am not using VR.  

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta]
 - A-4E Version [e.g. v1.3]

**Additional context**

**Comment by 08jne01** [comment] 2021-06-15 10:00
I don't see what the issue is in the video?

**Comment by vfaco** [comment] 2021-06-15 11:14
I agree -- it happens but does not appear in the track file. If/when it happens again I'll get another track.

**Comment by callmepartario** [comment] 2021-06-20 15:42
closing this issue due to lack of repoducibility, see #398

**Closed by callmepartario** 2021-06-20 15:42 UTC
Labels: Duplicate, TEST/reproduce
