### ISSUE TITLE
inconsistent behavior for slew knobs for waypoints D1 and D2

### ISSUE THREAD

**Issue by ToKeNeRd** [heclak/community-a4e-c#319] opened 2021-03-19 23:58 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.5.4.30386 Open Beta]
 - A-4E Version [e.g. v1.3]

**Additional context**

**Comment by callmepartario** [comment] 2021-03-28 00:09
unable to reproduce this myself, without additional details.

**Comment by callmepartario** [comment] 2021-03-29 13:33
The D1 knobs can be turned without pressing them; the D2 knobs require a press and hold to turn. Shouldn't the behavior of the two knobs be the same?

**Comment by 08jne01** [comment] 2021-04-05 14:41
Honestly reports without the proforma filled out are not worth investigating.

**Comment by callmepartario** [comment] 2021-04-05 14:43
normally i agree -- this one has been reported a few times in the discord chat, so i was just making notes to investigate on what can be reproduced later. i do think this one is a real issue; i meant to get to it this weekend but didn't manage to open DCS.

**Comment by 08jne01** [comment] 2021-04-05 14:44
Yea, fair enough.

**Comment by callmepartario** [comment] 2021-04-06 00:19
closing this issue, the knobs are working correctly. it's not D1 and D2 that are different, it's present and destination positions. the knobs operate differently and are working as they should.

**Closed by callmepartario** 2021-04-06 00:19 UTC
Labels: Bug, TEST/reproduce
