### ISSUE TITLE
TACAN and/or MCLS crash on Super Carrier

### ISSUE THREAD

**Issue by ericinexile** [heclak/community-a4e-c#575] opened 2022-11-06 15:49 UTC
**Describe the bug**
Game crash occurs after a few rotations of the TACAN selector out of "OFF"  Same is true with the MCLS (Ship-borne ILS).  In both cases, the frequency either doesn't matter or needs to be currently transmitting on the map.  In other words, I am unsure if the crash will occur if the receiver is set to a non-transmitting frequency.  But I do know that the crash will occur every time the selector is selected "ON" or "T/R" or "A/A" when an active frequency is tuned.

**To Reproduce**
Ramp start from the boat
Dial an active TACAN or boat ILS frequency
Turn MCLS "On" <or>
Turn TACAN to "T/R", "A/A" or "REC".
Sometimes multiple selections may be needed before the crash will occur.

**Expected behavior**
Game crashes to a freeze (not BSOD).

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.8.0.32235 Open Beta]
 - A-4E Version [e.g. v2.1]

**Additional context**

**Comment by twanmal** [comment] 2023-02-01 12:51
I could not reproduce this bug
A-4E-C_v2.1 and DCS build 2.8.2.35759

**Comment by callmepartario** [comment] 2023-05-11 02:15
i suspect a client/server mis-match here. if this error is not reproducible, i am going to close this one for now.

**Closed by callmepartario** 2023-05-11 02:15 UTC
Labels: TEST/reproduce
