### ISSUE TITLE
Unable to select CMPTR

### ISSUE THREAD

**Issue by 4535jacks** [heclak/community-a4e-c#301] opened 2021-02-14 00:21 UTC
**Describe the bug**
I am unable to turn the mode switch all the way to the right to CMPTR
**To Reproduce**
1. Any mission whether ramp or air start
2. Click on mode selector to turn to it to the right.
3. It only goes as far as BOMBS & GM ARM

**Expected behavior**
It should turn all the way round to CMPTR

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.60966
 - A-4E Version 2.0 Beta 2

**Additional context**

**Comment by 08jne01** [comment] 2021-02-14 00:25
Duplicate of #262 already known about.

**Closed by 08jne01** 2021-02-14 00:25 UTC
Labels: Duplicate
