### ISSUE TITLE
A-4E explodes upon carrier landing

### ISSUE THREAD

**Issue by qwmzy** [heclak/community-a4e-c#170] opened 2019-08-25 09:38 UTC
**Describe the bug**
A-4E explodes upon contact with carrier even when landing with suitable conditions

**To Reproduce**
1. Flaps down
2. hook down
3. gear down
4. enter groove to stennis
5. attempt to land

**Expected behavior**
a-4e to either catch a wire, or to perform a bolter and go around

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.5.5.34864 Open Beta
 - A-4E Version v1.3.1

**Additional context**
I've been playing dcs for years and perform carrier landings consistently with all modules that allow. However this seems to be the only one that performs as it does.

**Comment by DragonRoco** [comment] 2019-08-25 10:19
This is caused by the SFM (simple flight model) and an airstart in the mission editor. Any aircraft configured to start on the ground or on the carrier will trap fine. This is ED's bug and isn't fixable by this team, unless they move to a more complex flight model.

Airstarts below 50 knots may work fine.

**Comment by Cumulus7** [comment] 2019-10-07 20:39
Hi,
i seem to have the same problem. 
Using the supplied Quick-Start mission i explode on every landing attempt.
Gear is down. Hook extended. Slow speed.... -> BOOM.

Does this quickstart mission work for anyone?
(Fresh install of DCS and the A4)

Greetings,
Markus

**Comment by heclak** [comment] 2019-12-17 07:29
Duplicate of #109

**Closed by heclak** 2019-12-17 07:29 UTC
Labels: DCS Bug, bug
