### ISSUE TITLE
When twisting the gunsight light knob all the screen turns black.

### ISSUE THREAD

**Issue by Brojustuserandomgenerationusername** [heclak/community-a4e-c#252] opened 2020-09-25 06:08 UTC
Using DCS stable (non beta/alpha) 2.5.6.52437
A-4E 1.4.1

All settings on min possible (shit computer)
on an AMD 6950 with 16gb of DDR3 RAM and a i5 2500k with a 250gb SSD
Windows 7 Pro 64bit version.

Full screen on 1080p 16:9 monitor with vsync enabled. Steam version of the game.

Whenever i use the mouse to drag the gunsight light indicator to the left of the reticle too much to the left or the right the entire first person camera becomes a black screen where only the crosshair mouse cursor is visible. No this isn't a passed out over G effect because i can still fly the plane fine and using external view everything is normal, but in first person everything is a black screen of which i cant escape unless i find that knob again by pure luck.

This issue ONLY happens when the plane is on and running. When doing a cold start or shutting the engines the gunsight light knob does not do this.
![20200925030657_1](https://user-images.githubusercontent.com/65527604/94232430-5b862680-fedc-11ea-883a-d0f8ec5f7dbc.jpg)
Missing in the picture is the green knob mouse cursor, thought it would be captured in the steam screenshot.

**Comment by heclak** [comment] 2020-09-30 00:32
Going to need to get someone to be able to recreate this first. Still looking into it.

**Comment by Brojustuserandomgenerationusername** [comment] 2020-09-30 10:34
Im afraid i am unable to keep trying to test the mod and the game, but i missed the chance to do a test during the starting or shut down of engines.

**Comment by callmepartario** [comment] 2020-10-19 21:21
i can't help but wonder if there's a graphics driver issue going on here, and that is what is messing with DCS overlay draw. is it becoming gradually darker if you turn the knob, or just disappearing altogether like turning off a light switch?

**Comment by Brojustuserandomgenerationusername** [comment] 2020-10-20 07:44
Disappears outright from frame to frame if i turn the knob too much. Could be a driver issue, im in an AMD card after all.

**Comment by 08jne01** [comment] 2021-02-13 03:21
Closing this issue since no one else has been able to reproduce it.

**Closed by 08jne01** 2021-02-13 03:21 UTC
Labels: TEST/reproduce
