### ISSUE TITLE
Wrong longitude hemisphere displayed on kneeboard (Nevada)

### ISSUE THREAD

**Issue by ataribaby42** [heclak/community-a4e-c#467] opened 2022-01-02 19:02 UTC
**Describe the bug**
Longitude should be West and not East on kneeboard, on dials in cockpit it is correctly as W.

**To Reproduce**
1. Spawn on Nellis with A-4 with at least one waypoint
2. Check Kneeboard

**Expected behavior**
Kneeboard should follow real Longitude same as dial in cockpit.

**Screenshots**
![long2](https://user-images.githubusercontent.com/54838824/147886555-0a7fe74d-3dcf-4259-9d51-4a53962fad06.jpg)

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.7.9.18080  Open Beta
 - A-4E Version 2.0

**Comment by callmepartario** [comment] 2022-01-02 19:11
duplicate, see #466 - i beat you to the punch on filing this one!

**Comment by derbuur** [comment] 2022-01-09 04:03
I've searching now more than 4 hours for the failure but without success.
I think the problem is in the function  "lo_to_geo_coords". The following function "get_digits_LL122" or "LL123" expect negative values for southern and western hemisphere but the function "lo_to_geo_coords" gives only positive values even south or west.
I do not found the function "lo_to_geo_coords" in the code or documentation, so I could not see if there is an other variable for north/south or east/west.
So, if anybody knows how the function "lo_to_geo_coords" works or where i can find an example, please give me a hind.

**Comment by callmepartario** [comment] 2022-01-10 22:06
hm. interesting. perhaps we can read the map region and set them by that - at the moment no maps cross the equator or the hemisphere line, so i think we're in the clear.

**Comment by callmepartario** [comment] 2022-01-13 23:32
closing this in favor of #477 - this issue has been fixed.

**Closed by callmepartario** 2022-01-13 23:32 UTC
Labels: Duplicate
