### ISSUE TITLE
Catapult Launch doesn't work since DCS 2.5.6.54046 Open Beta

### ISSUE THREAD

**Issue by rudel-chw** [heclak/community-a4e-c#245] opened 2020-08-26 21:44 UTC
**Describe the bug**
After today's DCS update (to version DCS 2.5.6.54046 OB), the Hook command (U key) doesn't work on the Stennis. The aircraft doesn't latch to the Catapult and starts sliding backwards, even if the aircraft was set to start from catapult. This was working fine until prior version.

**To Reproduce**
1. Start a mission with an A-4E set to take off from runway, on the Stennis.
2. The aircraft begins to roll back and the command U doesn't latch the aircraft to the Catapult.
3. The Salute command doesn't trigger the catapult and the aircraft goes straignt onto the water.

**Expected behavior**
Up until the prior version of DCS, the aircraft started latched onto the catapult and the Salute command made the catapult launch the plane.

**Screenshots**
The screenshot shows the aircraft leaving the deck, the catapult trolley isnt there and the IAS is too low.

**Software Information (please complete the following information):**
 - DCS Version: DCS 2.5.6.54046 Open Beta
 - A-4E Version: 1.4
![Launch](https://user-images.githubusercontent.com/51679833/91360039-b89a9980-e7c3-11ea-98f6-f849027751da.jpg)

**Additional context**

**Comment by callmepartario** [comment] 2020-08-26 23:20
just chipping in to confirm this is also happening to me.

**Comment by callmepartario** [comment] 2020-08-27 01:26
Reports that TACAN and NAV computer functions are also affected. Requesting additional reproduction.

**Comment by FluerdeLune** [comment] 2020-08-27 02:29
I found a temporary remedy for the catapult launch.
(Bypass Catapult Alignment Check mush be enabled and manual launch)
**Steps:**
1. Start Instant Action "Carrier Launch"
2.Hold the brakes then press "FLY"
3. Press "U" 3x (Hook, Unhook, Hook)
4. While on full power "Salute!"

**Comment by robscallsign** [comment] 2020-08-27 16:18
I am able to reproduce:
* Starting on the carrier you are not held in the catapult
* When you try to get latched to the catapult with the 'u' key the text comes up "You are hooked in" but you will continue to roll backwards
* LALT+U no longer seems to activate the catapult launch.  You can still take off by throttling up, releasing the brakes, and you still get the extra speed boost at the end of the deck, but the speed at which you accelerate down the deck doesn't seem to have the "After Burner Boost" applied so you are much slower when you get in the air.

TACAN/ILS:
* Using a mission that I've frequently flown CASE1 and CASE3 approaches at the Stennis with the A-4 using both TACAN and the ILS several times, I could get neither to work, the mission has been unmodified or changed since the time it was working. 
* I believe this has stopped with the introduction of the last two patches that have involved the Syria map.
* Noticed that the Glideslope/Localizer bars (Chickensticks) were visible on the ADF - usually they aren't there
* Tried to make a new mission in the Caucasus at Sochi, set TACAN to 47X, it would not turn 
* Made a new mission with a hot A-4 on the runway at Sochi and tried to tune Tacan 47X, Tacan would not turn on


The two test missions, one with the Stennis (Tacan 74X), and one with a hot A-4 at Sochi to try 47X are attached:

[cqwcotw_A4_Stennis.zip](https://github.com/heclak/community-a4e-c/files/5137572/cqwcotw_A4_Stennis.zip)
[Tacan_A4_Sochi.zip](https://github.com/heclak/community-a4e-c/files/5137579/Tacan_A4_Sochi.zip)

**Comment by heclak** [comment] 2020-09-19 05:55
The catapult issue has been fixed but it seems like there might still be some issues with the TACAN positioning for carrier. It doesn't update as the carrier move. It would be great if I could get some help tracking down some of the remaining issues.

**Comment by 08jne01** [comment] 2021-02-12 02:53
This will be fixed for the EFM, but looks relevant to #282. Closing since this is now fixed.

**Closed by 08jne01** 2021-02-12 02:53 UTC
Labels: Bug, Code/EFM, Need Input
